#!/usr/bin/env bash
#
# Print the fork's merge invariants as VALUES, not paths.
#
# A Kotlin Multiplatform flip moves nearly every file, so a path-based diff reports the whole
# tree as changed and hides the one line that really moved. This script prints the values the
# fork must keep across a merge, so two runs can be compared with:
#
#     scripts/merge_invariants.sh premerge-dev-<date> > /tmp/inv_pre.txt
#     scripts/merge_invariants.sh post                  > /tmp/inv_post.txt
#     git diff --no-index /tmp/inv_pre.txt /tmp/inv_post.txt
#
# Every line that differs must be explained. Line numbers are deliberately not printed.
#
# Usage: scripts/merge_invariants.sh <rev|post>

set -u

REV="${1:-post}"

# `post` means the working tree; any other value is a revision.
#
# `post` reads the files on disk and not `HEAD`, because the merge is normally still uncommitted
# when this is run - HEAD would then be the pre-merge commit and every section would report the
# old values, which reads as "the merge changed nothing". Same reason the empty AT makes
# `git grep` read the working tree instead of a commit.
if [ "$REV" = "post" ]; then
    AT=""
    show_file() {
        cat "$1" 2>/dev/null
    }
else
    AT="$REV"
    show_file() {
        git show "$REV:$1" 2>/dev/null
    }
fi

# grep from the chosen revision, one match per line, without "file:line:" prefixes.
g() {
    # shellcheck disable=SC2086
    git grep -h -E "$1" $AT -- "$2" 2>/dev/null | sed 's/^[[:space:]]*//' | sort -u
}

# grep with the file name kept, for mappings where the path is part of the value.
gf() {
    # shellcheck disable=SC2086
    git grep -l -E "$1" $AT -- "$2" 2>/dev/null | sort
}

# count matches (nil if the revision does not have the file at all)
c() {
    # shellcheck disable=SC2086
    git grep -c -E "$1" $AT -- "$2" 2>/dev/null | wc -l
}

section() {
    echo
    echo "### $1"
}

echo "# fork invariants of: ${REV}"
echo "# generated by scripts/merge_invariants.sh"

section "included modules (settings.gradle)"
# Groovy style: include ':app' / include ':a', ':b' (not the Kotlin `include(":app")` form).
show_file settings.gradle | grep -oE "^include .*" | sed "s/^include //;s/'//g;s/,/\n/g;s/^ *//" | grep -v '^$' | sort

section "fork CGM modules present"
for m in eversense dexcom_oneplus libre3 libkeks; do
    echo "plugins/$m: $(gf ".*" "plugins/$m/**" | wc -l) files"
done

section "SourceSensor entries"
g '^[[:space:]]*[A-Z_0-9]+[(,]' '*/source/SourceSensor.kt'

section "plugin @IntKey registrations (key, plugin)"
g 'IntKey\([0-9]+\)' '*.kt' | grep -oE 'IntKey\([0-9]+\)'

section "AIMI file count"
echo "openAPSAIMI files: $(gf 'openAPSAIMI' '*/openAPSAIMI/**' | wc -l)"

section "adaptive smoothing calibration source (calibratedOrValue)"
g 'calibratedOrValue' '*.kt' | wc -l

section "dashboard skins"
g 'dashboardOverview|SkinDescriptionProvider|SkinInterface' '*.kt' | wc -l

section "manifest ML / physio / notification-reader permissions"
for f in app/src/main/AndroidManifest.xml wear/src/main/AndroidManifest.xml; do
    echo "-- $f"
    # shellcheck disable=SC2086
    show_file "$f" | grep -oE 'android:name="android.permission.[A-Z_]+"' | sort -u
done

section "hormonitor patient_story block"
g 'patient_story' '*.kt'

section "database maintenance gate (must stay runVacuum = false)"
g 'runVacuum' '*.kt'
echo "-- VACUUM outside the manual path (expect none):"
g 'VACUUM' '*.kt'

section "DataInbox drain() call sites"
gf 'drain\(\)' '*.kt' | sed 's|.*/||' | sort

section "notification-reader remaps"
g 'com\.dexcom\.|com\.medtronic|com\.google\.android\.apps\.ng|com\.ambrosia|com\.liberty|com\.everisonsense' '*.kt' | sort -u

section "NotificationId enum order (the id is the ordinal)"
# shellcheck disable=SC2086
show_file core/interfaces/src/commonMain/kotlin/app/aaps/core/interfaces/notifications/NotificationId.kt \
    | grep -oE '^[[:space:]]*[A-Z][A-Z_0-9]+\(' | sed 's/[[:space:]]*(//'

section "libre3 gate defaults"
g 'UseRealSkeleton' '*.kt'
g 'LIBRE3_DIR_ACCESS_LOST' '*.kt'

section "strings that must not be lost (key counts)"
for f in core/interfaces/src/androidMain/res/values/strings.xml \
         implementation/src/androidMain/res/values/strings.xml \
         plugins/sync/src/androidMain/res/values/strings.xml \
         wear/src/main/res/values/strings.xml \
         plugins/source/src/androidMain/res/values/strings.xml; do
    # shellcheck disable=SC2086
    n=$(show_file "$f" | grep -cE '<string name=')
    echo "$f: $n"
done

echo
echo "# end"
