package app.aaps.core.keys

import app.aaps.core.keys.interfaces.BooleanPreferenceKey
import app.aaps.core.keys.interfaces.DoublePreferenceKey
import app.aaps.core.keys.interfaces.SyncChannel
import app.aaps.core.keys.interfaces.SyncDirection
import app.aaps.core.keys.interfaces.SyncSpec
import app.aaps.core.keys.interfaces.TextRef

enum class DoubleKey(
    override val key: String,
    override val defaultValue: Double,
    override val min: Double,
    override val max: Double,
    override val title: TextRef,
    override val summary: TextRef? = null,
    override val preferenceType: PreferenceType = PreferenceType.TEXT_FIELD,
    override val defaultedBySM: Boolean = false,
    override val calculatedBySM: Boolean = false,
    override val dependency: BooleanPreferenceKey? = null,
    override val hideParentScreenIfHidden: Boolean = false,
    override val unitType: UnitType = UnitType.NONE,
    override val sync: SyncSpec? = null
) : DoublePreferenceKey {

    OverviewInsulinButtonIncrement1(
        key = "insulin_button_increment_1",
        defaultValue = 0.5,
        min = -5.0,
        max = 5.0,
        title = KeysStrings.pref_title_insulin_button_increment_1,
        summary = KeysStrings.insulin_increment_button_message,
        defaultedBySM = true,
        dependency = BooleanKey.OverviewShowInsulinButton,
        unitType = UnitType.INSULIN,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    OverviewInsulinButtonIncrement2(
        key = "insulin_button_increment_2",
        defaultValue = 1.0,
        min = -5.0,
        max = 5.0,
        title = KeysStrings.pref_title_insulin_button_increment_2,
        summary = KeysStrings.insulin_increment_button_message,
        defaultedBySM = true,
        dependency = BooleanKey.OverviewShowInsulinButton,
        unitType = UnitType.INSULIN,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    OverviewInsulinButtonIncrement3(
        key = "insulin_button_increment_3",
        defaultValue = 2.0,
        min = -5.0,
        max = 5.0,
        title = KeysStrings.pref_title_insulin_button_increment_3,
        summary = KeysStrings.insulin_increment_button_message,
        defaultedBySM = true,
        dependency = BooleanKey.OverviewShowInsulinButton,
        unitType = UnitType.INSULIN,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ActionsFillButton1(key = "fill_button1", defaultValue = 0.3, min = 0.05, max = 20.0, title = KeysStrings.pref_title_fill_button_1, defaultedBySM = true, hideParentScreenIfHidden = true, unitType = UnitType.INSULIN),
    ActionsFillButton2(key = "fill_button2", defaultValue = 0.0, min = 0.0, max = 20.0, title = KeysStrings.pref_title_fill_button_2, defaultedBySM = true, unitType = UnitType.INSULIN),
    ActionsFillButton3(key = "fill_button3", defaultValue = 0.0, min = 0.0, max = 20.0, title = KeysStrings.pref_title_fill_button_3, defaultedBySM = true, unitType = UnitType.INSULIN),
    SafetyMaxBolus(key = "treatmentssafety_maxbolus", defaultValue = 3.0, min = 0.1, max = 60.0, title = KeysStrings.pref_title_max_bolus, unitType = UnitType.INSULIN, sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)),
    ApsMaxBasal(
        key = "openapsma_max_basal",
        defaultValue = 1.0,
        min = 0.1,
        max = 25.0,
        title = KeysStrings.pref_title_max_basal,
        summary = KeysStrings.openapsma_max_basal_summary,
        defaultedBySM = true,
        calculatedBySM = true,
        unitType = UnitType.INSULIN_RATE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsSmbMaxIob(
        key = "openapsmb_max_iob",
        defaultValue = 3.0,
        min = 0.0,
        max = 70.0,
        title = KeysStrings.pref_title_smb_max_iob,
        summary = KeysStrings.openapssmb_max_iob_summary,
        defaultedBySM = true,
        calculatedBySM = true,
        unitType = UnitType.INSULIN,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAmaMaxIob(
        key = "openapsma_max_iob",
        defaultValue = 1.5,
        min = 0.0,
        max = 25.0,
        title = KeysStrings.pref_title_ama_max_iob,
        summary = KeysStrings.openapsma_max_iob_summary,
        defaultedBySM = true,
        calculatedBySM = true,
        unitType = UnitType.INSULIN,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsMaxDailyMultiplier(
        key = "openapsama_max_daily_safety_multiplier",
        defaultValue = 3.0,
        min = 1.0,
        max = 10.0,
        title = KeysStrings.pref_title_max_daily_multiplier,
        summary = KeysStrings.openapsama_max_daily_safety_multiplier_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsMaxCurrentBasalMultiplier(
        key = "openapsama_current_basal_safety_multiplier",
        defaultValue = 4.0,
        min = 1.0,
        max = 10.0,
        title = KeysStrings.pref_title_current_basal_multiplier,
        summary = KeysStrings.openapsama_current_basal_safety_multiplier_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAmaBolusSnoozeDivisor(
        key = "bolussnooze_dia_divisor",
        defaultValue = 2.0,
        min = 1.0,
        max = 10.0,
        title = KeysStrings.pref_title_bolus_snooze_divisor,
        summary = KeysStrings.openapsama_bolus_snooze_dia_divisor_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAmaMin5MinCarbsImpact(
        key = "openapsama_min_5m_carbimpact",
        defaultValue = 3.0,
        min = 1.0,
        max = 12.0,
        title = KeysStrings.pref_title_ama_min_5m_carbs_impact,
        summary = KeysStrings.openapsama_min_5m_carb_impact_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsSmbMin5MinCarbsImpact(
        key = "openaps_smb_min_5m_carbimpact",
        defaultValue = 8.0,
        min = 1.0,
        max = 12.0,
        title = KeysStrings.pref_title_smb_min_5m_carbs_impact,
        summary = KeysStrings.openapsama_min_5m_carb_impact_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    AbsorptionCutOff(
        key = "absorption_cutoff",
        defaultValue = 6.0,
        min = 4.0,
        max = 10.0,
        title = KeysStrings.pref_title_absorption_cutoff,
        summary = KeysStrings.absorption_cutoff_summary,
        unitType = UnitType.HOURS_DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    AbsorptionMaxTime(
        key = "absorption_maxtime",
        defaultValue = 6.0,
        min = 4.0,
        max = 10.0,
        title = KeysStrings.pref_title_absorption_maxtime,
        summary = KeysStrings.absorption_max_time_summary,
        unitType = UnitType.HOURS_DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    AutosensMin(
        key = "autosens_min",
        defaultValue = 0.7,
        min = 0.1,
        max = 1.0,
        title = KeysStrings.pref_title_autosens_min,
        summary = KeysStrings.openapsama_autosens_min_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    AutosensMax(
        key = "autosens_max",
        defaultValue = 1.2,
        min = 0.5,
        max = 3.0,
        title = KeysStrings.pref_title_autosens_max,
        summary = KeysStrings.openapsama_autosens_max_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfMin(
        key = "autoISF_min",
        defaultValue = 1.0,
        min = 0.3,
        max = 1.0,
        title = KeysStrings.pref_title_autoisf_min,
        summary = KeysStrings.openapsama_autoISF_min_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfMax(
        key = "autoISF_max",
        defaultValue = 1.0,
        min = 1.0,
        max = 3.0,
        title = KeysStrings.pref_title_autoisf_max,
        summary = KeysStrings.openapsama_autoISF_max_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfBgAccelWeight(
        key = "bgAccel_ISF_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 1.0,
        title = KeysStrings.pref_title_bg_accel_weight,
        summary = KeysStrings.openapsama_bgAccel_ISF_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfBgBrakeWeight(
        key = "bgBrake_ISF_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 1.0,
        title = KeysStrings.pref_title_bg_brake_weight,
        summary = KeysStrings.openapsama_bgBrake_ISF_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfLowBgWeight(
        key = "lower_ISFrange_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 2.0,
        title = KeysStrings.pref_title_low_bg_weight,
        summary = KeysStrings.openapsama_lower_ISFrange_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfHighBgWeight(
        key = "higher_ISFrange_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 2.0,
        title = KeysStrings.pref_title_high_bg_weight,
        summary = KeysStrings.openapsama_higher_ISFrange_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfSmbDeliveryRatioBgRange(
        key = "openapsama_smb_delivery_ratio_bg_range",
        defaultValue = 0.0,
        min = 0.0,
        max = 100.0,
        title = KeysStrings.pref_title_smb_delivery_ratio_bg_range,
        summary = KeysStrings.openapsama_smb_delivery_ratio_bg_range_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfPpWeight(
        key = "pp_ISF_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 0.15,
        title = KeysStrings.pref_title_pp_weight,
        summary = KeysStrings.openapsama_pp_ISF_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_3,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfDuraWeight(
        key = "dura_ISF_weight",
        defaultValue = 0.0,
        min = 0.0,
        max = 3.0,
        title = KeysStrings.pref_title_dura_weight,
        summary = KeysStrings.openapsama_dura_ISF_weight_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfSmbDeliveryRatio(
        key = "openapsama_smb_delivery_ratio",
        defaultValue = 0.5,
        min = 0.1,
        max = 1.0,
        title = KeysStrings.pref_title_smb_delivery_ratio,
        summary = KeysStrings.openapsama_smb_delivery_ratio_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfSmbDeliveryRatioMin(
        key = "openapsama_smb_delivery_ratio_min",
        defaultValue = 0.5,
        min = 0.1,
        max = 1.0,
        title = KeysStrings.pref_title_smb_delivery_ratio_min,
        summary = KeysStrings.openapsama_smb_delivery_ratio_min_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfSmbDeliveryRatioMax(
        key = "openapsama_smb_delivery_ratio_max",
        defaultValue = 0.5,
        min = 0.5,
        max = 1.0,
        title = KeysStrings.pref_title_smb_delivery_ratio_max,
        summary = KeysStrings.openapsama_smb_delivery_ratio_max_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE_2,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsAutoIsfSmbMaxRangeExtension(
        key = "openapsama_smb_max_range_extension",
        defaultValue = 1.0,
        min = 1.0,
        max = 5.0,
        title = KeysStrings.pref_title_smb_max_range_extension,
        summary = KeysStrings.openapsama_smb_max_range_extension_summary,
        defaultedBySM = true,
        unitType = UnitType.DOUBLE,
        sync = SyncSpec(SyncChannel.Cold, SyncDirection.Bidirectional)
    ),
    ApsBoostV6PreMealLeadMin( title = KeysStrings.boost_v6_pre_meal_lead_min_title, key = "boost_v6_pre_meal_lead_min", defaultValue = 60.0, min = 30.0, max = 90.0, summary = KeysStrings.pref_summary_boost_v6_pre_meal_lead, unitType = UnitType.MIN),
    ApsBoostV6PreMealTargetMgdl( title = KeysStrings.boost_v6_pre_meal_target_mgdl_title, key = "boost_v6_pre_meal_target_mgdl", defaultValue = 72.0, min = 65.0, max = 90.0, summary = KeysStrings.pref_summary_boost_v6_pre_meal_target, unitType = UnitType.MGDL),
    ApsBoostV5Sensitivity( title = KeysStrings.boost_v5_sensitivity_title, key = "boost_v5_sensitivity", defaultValue = 1.0, min = 0.8, max = 1.2, summary = KeysStrings.pref_summary_boost_v5_sensitivity, unitType = UnitType.DOUBLE),
    ApsBoostV5HypoCaution( title = KeysStrings.boost_v5_hypo_caution_title, key = "boost_v5_hypo_caution", defaultValue = 1.0, min = 1.0, max = 2.0, summary = KeysStrings.pref_summary_boost_v5_hypo_caution, unitType = UnitType.DOUBLE),
    ApsBoostV5PrimerCapU( "boost_v5_primer_cap_u", 0.0, 0.0, 1.0, title = TextRef.Literal(""), defaultedBySM = true, unitType = UnitType.INSULIN),
    ApsBoostV5CommittedCapU( title = TextRef.Literal(""), key = "boost_v5_committed_cap_u", defaultValue = 0.5, min = 0.0, max = 2.5, summary = KeysStrings.pref_summary_boost_v5_committed_cap, unitType = UnitType.INSULIN),
    ApsBoostV5ConfirmedCapU( title = TextRef.Literal(""), key = "boost_v5_confirmed_cap_u", defaultValue = 2.5, min = 0.0, max = 7.5, summary = KeysStrings.pref_summary_boost_v5_confirmed_cap, unitType = UnitType.INSULIN),
    ApsBoostV5Aggression( title = KeysStrings.boost_v5_aggression_title, key = "boost_v5_aggression", defaultValue = 1.0, min = 0.7, max = 1.6, summary = KeysStrings.pref_summary_boost_v5_aggression, unitType = UnitType.DOUBLE_2),
    ApsBoostCumulativeSmbCap60Min( title = TextRef.Literal(""), key = "boost_cumulative_smb_cap_60min", defaultValue = 10.0, min = 0.0, max = 10.0, summary = KeysStrings.pref_summary_boost_smb_cap_60min, unitType = UnitType.INSULIN),
    ApsBoostPostExerciseRecoveryScale( title = TextRef.Literal(""), key = "boost_post_exercise_recovery_scale", defaultValue = 0.5, min = 0.0, max = 1.0, summary = KeysStrings.pref_summary_boost_post_exercise_scale, unitType = UnitType.DOUBLE),
    ApsBoostPostExerciseRecoveryHours( title = TextRef.Literal(""), key = "boost_post_exercise_recovery_hours", defaultValue = 2.0, min = 0.5, max = 8.0, summary = KeysStrings.pref_summary_boost_post_exercise_hours, unitType = UnitType.HOURS_DOUBLE),
    ApsBoostActivityPct( title = KeysStrings.boost_activity_pct_title, key = "boost_activity_pct", defaultValue = 80.0, min = 30.0, max = 150.0, summary = KeysStrings.pref_summary_boost_activity_pct, unitType = UnitType.PERCENT),
    ApsBoostInactivityPct( title = KeysStrings.boost_inactivity_pct_title, key = "boost_inactivity_pct", defaultValue = 130.0, min = 100.0, max = 200.0, summary = KeysStrings.pref_summary_boost_inactivity_pct, unitType = UnitType.PERCENT),
    ApsBoostSleepInHours( title = KeysStrings.boost_sleep_in_hrs_title, key = "boost_sleep_in_hrs", defaultValue = 2.0, min = 0.0, max = 18.0, summary = KeysStrings.pref_summary_boost_sleep_in_hrs, unitType = UnitType.HOURS_DOUBLE),
    ApsBoostDynIsfVelocity( title = KeysStrings.boost_dynisf_velocity_title, key = "boost_dynisf_velocity", defaultValue = 100.0, min = 0.0, max = 100.0, summary = KeysStrings.pref_summary_boost_dynisf_velocity, unitType = UnitType.PERCENT),
    ApsBoostPercentScale( title = TextRef.Literal(""), key = "boost_percent_scale_factor", defaultValue = 200.0, min = 50.0, max = 500.0, summary = KeysStrings.pref_summary_boost_percent_scale_factor, unitType = UnitType.PERCENT),
    ApsBoostScale( title = TextRef.Literal(""), key = "boost_scale_value", defaultValue = 1.0, min = 0.1, max = 3.0, summary = KeysStrings.pref_summary_boost_scale, unitType = UnitType.DOUBLE),
    ApsBoostInsulinReqPct( title = TextRef.Literal(""), key = "boost_insulin_req_pct", defaultValue = 50.0, min = 30.0, max = 100.0, summary = KeysStrings.pref_summary_boost_insulin_req_pct, unitType = UnitType.PERCENT),
    ApsBoostMaxIob( title = KeysStrings.boost_max_iob_title, key = "boost_max_iob", defaultValue = 1.0, min = 0.1, max = 12.0, summary = KeysStrings.pref_summary_boost_max_iob, unitType = UnitType.INSULIN),
    ApsBoostBolus( title = TextRef.Literal(""), key = "boost_bolus_cap", defaultValue = 2.5, min = 0.1, max = 10.0, summary = KeysStrings.pref_summary_boost_bolus_cap, unitType = UnitType.INSULIN),
    InactivityScaleFactor( key = "inactivity_scale_factor", defaultValue = 1.0, min = 0.0, max = 1.5, title = TextRef.Literal(""), summary = KeysStrings.pref_activ_mon_sum_inactivity_scale_factor, defaultedBySM = true, dependency = BooleanKey.ActivityMonitorDetection, unitType = UnitType.DOUBLE),
    ActivityScaleFactor( key= "activity_scale_factor", defaultValue = 1.0, min = 0.0, max = 1.5, title = TextRef.Literal(""), summary = KeysStrings.pref_activ_mon_sum_activity_scale_factor, defaultedBySM = true, dependency = BooleanKey.ActivityMonitorDetection, unitType = UnitType.DOUBLE),
    OApsAIMIGovernanceAnticipationDecayBlendMax( key = "key_aimi_gov_anticipation_decay_blend_max", defaultValue = 0.50, min = 0.0, max = 1.0, title = KeysStrings.aimi_gov_anticipation_decay_blend_max_title, summary = KeysStrings.aimi_gov_anticipation_decay_blend_max_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceAnticipationHypoDamp( key = "key_aimi_gov_anticipation_hypo_damp", defaultValue = 0.55, min = 0.0, max = 0.95, title = KeysStrings.aimi_gov_anticipation_hypo_damp_title, summary = KeysStrings.aimi_gov_anticipation_hypo_damp_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceAnticipationMarginMgdl( key = "key_aimi_gov_anticipation_margin_mgdl", defaultValue = 12.0, min = 0.0, max = 40.0, title = KeysStrings.aimi_gov_anticipation_margin_mgdl_title, summary = KeysStrings.aimi_gov_anticipation_margin_mgdl_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.MGDL),
    OApsAIMIGovernanceAnticipationLookbackSamples( key = "key_aimi_gov_anticipation_lookback_samples", defaultValue = 18.0, min = 6.0, max = 96.0, title = KeysStrings.aimi_gov_anticipation_lookback_samples_title, summary = KeysStrings.aimi_gov_anticipation_lookback_samples_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE),
    OApsAIMIGovernanceHoldAggDecaySevere( key = "key_aimi_gov_hold_agg_decay_severe", defaultValue = 0.965, min = 0.90, max = 0.999, title = KeysStrings.aimi_gov_hold_agg_decay_severe_title, summary = KeysStrings.aimi_gov_hold_agg_decay_severe_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldAggFloorSevere( key = "key_aimi_gov_hold_agg_floor_severe", defaultValue = 0.72, min = 0.50, max = 0.90, title = KeysStrings.aimi_gov_hold_agg_floor_severe_title, summary = KeysStrings.aimi_gov_hold_agg_floor_severe_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldBasalDecaySevere( key = "key_aimi_gov_hold_basal_decay_severe", defaultValue = 0.975, min = 0.90, max = 0.999, title = KeysStrings.aimi_gov_hold_basal_decay_severe_title, summary = KeysStrings.aimi_gov_hold_basal_decay_severe_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldBasalFloorSevere( key = "key_aimi_gov_hold_basal_floor_severe", defaultValue = 0.88, min = 0.80, max = 0.95, title = KeysStrings.aimi_gov_hold_basal_floor_severe_title, summary = KeysStrings.aimi_gov_hold_basal_floor_severe_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldAggDecayRate( key = "key_aimi_gov_hold_agg_decay_rate", defaultValue = 0.97, min = 0.90, max = 0.999, title = KeysStrings.aimi_gov_hold_agg_decay_rate_title, summary = KeysStrings.aimi_gov_hold_agg_decay_rate_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldAggFloorRate( key = "key_aimi_gov_hold_agg_floor_rate", defaultValue = 0.70, min = 0.50, max = 0.90, title = KeysStrings.aimi_gov_hold_agg_floor_rate_title, summary = KeysStrings.aimi_gov_hold_agg_floor_rate_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldBasalDecayRate( key = "key_aimi_gov_hold_basal_decay_rate", defaultValue = 0.98, min = 0.90, max = 0.999, title = KeysStrings.aimi_gov_hold_basal_decay_rate_title, summary = KeysStrings.aimi_gov_hold_basal_decay_rate_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHoldBasalFloorRate( key = "key_aimi_gov_hold_basal_floor_rate", defaultValue = 0.85, min = 0.80, max = 0.95, title = KeysStrings.aimi_gov_hold_basal_floor_rate_title, summary = KeysStrings.aimi_gov_hold_basal_floor_rate_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceSevereHypoBgMgdl(
        key = "key_aimi_gov_severe_hypo_bg_mgdl",
        defaultValue = 70.0,
        min = 54.0,
        max = 85.0,
        title = KeysStrings.aimi_gov_severe_hypo_bg_mgdl_title,
        summary = KeysStrings.aimi_gov_severe_hypo_bg_mgdl_summary,
        dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled,
        unitType = UnitType.MGDL),
    OApsAIMIGovernanceHypoBgMgdl(
        key = "key_aimi_gov_hypo_bg_mgdl",
        defaultValue = 80.0,
        min = 65.0,
        max = 100.0,
        title = KeysStrings.aimi_gov_hypo_bg_mgdl_title,
        summary = KeysStrings.aimi_gov_hypo_bg_mgdl_summary,
        dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled,
        unitType = UnitType.MGDL),
    OApsAIMIGovernanceHypoRateExit( key = "key_aimi_gov_hypo_rate_exit", defaultValue = 0.12, min = 0.02, max = 0.44, title = KeysStrings.aimi_gov_hypo_rate_exit_title, summary = KeysStrings.aimi_gov_hypo_rate_exit_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIGovernanceHypoRateEnter( key = "key_aimi_gov_hypo_rate_enter", defaultValue = 0.20, min = 0.05, max = 0.45, title = KeysStrings.aimi_gov_hypo_rate_enter_title, summary = KeysStrings.aimi_gov_hypo_rate_enter_summary, preferenceType = PreferenceType.TEXT_FIELD, dependency = BooleanKey.OApsAIMIT3cAdaptiveBasalEnabled, unitType = UnitType.DOUBLE_2),
    OApsAIMIAdaptiveBasalMaxScaling(
        key = "key_aimi_adaptive_basal_max_scaling",
        defaultValue = 1.3,
        min = 0.5,
        max = 2.0,
        title = KeysStrings.pref_title_aimi_adaptive_basal_max_scaling,
        summary = KeysStrings.pref_summary_aimi_adaptive_basal_max_scaling,
        unitType = UnitType.DOUBLE),
    OApsAIMIUndeclaredCobMaxG(
        "key_aimi_undeclared_cob_max_g", 25.0, 5.0, 80.0,
        title = KeysStrings.pref_title_aimi_undeclared_cob_max_g,
        summary = KeysStrings.pref_summary_aimi_undeclared_cob_max_g,
        dependency = BooleanKey.OApsAIMIUndeclaredCobEnabled,
        unitType = UnitType.GRAMS),
    OApsAIMIT3cCfrdCobDelayMin(
        key = "key_aimi_t3c_cfrd_cob_delay_min",
        defaultValue = 30.0,
        min = 0.0,
        max = 90.0,
        title = KeysStrings.pref_title_aimi_t3c_cfrd_cob_delay,
        summary = KeysStrings.pref_summary_aimi_t3c_cfrd_cob_delay,
        dependency = BooleanKey.OApsAIMIT3cCfrdMode,
        unitType = UnitType.MIN),
    OApsAIMIT3cCfrdLgsFloorMgdl(
        key = "key_aimi_t3c_cfrd_lgs_floor",
        defaultValue = 95.0,
        min = 70.0,
        max = 95.0,
        title = KeysStrings.pref_title_aimi_t3c_cfrd_lgs_floor,
        summary = KeysStrings.pref_summary_aimi_t3c_cfrd_lgs_floor,
        dependency = BooleanKey.OApsAIMIT3cCfrdMode,
        unitType = UnitType.MGDL),
    OApsAIMIT3cAggressiveness( "key_aimi_t3c_aggressiveness", 1.0, 0.5, 3.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIT3cAnticipationStrength( "key_aimi_t3c_anticipation_strength", 0.0, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIT3cActivationThreshold( "key_aimi_t3c_activation_threshold", 130.0, 100.0, 250.0, title = TextRef.Literal(""), unitType = UnitType.MGDL),
    AimiTubeKappaSafetyMargin(
        key = "key_aimi_tube_kappa_margin",
        defaultValue = 0.08,
        min = 0.0,
        max = 0.35,
        title = KeysStrings.aimi_tube_kappa_margin_title,
        summary = KeysStrings.aimi_tube_kappa_margin_summary,
        dependency = BooleanKey.OApsAIMIStraightLineTubeAdvisorEnabled,
        unitType = UnitType.DOUBLE_2),
    AimiTubeBasalTrimMax(
        key = "key_aimi_tube_basal_trim_max",
        defaultValue = 0.12,
        min = 0.0,
        max = 0.25,
        title = KeysStrings.aimi_tube_basal_trim_title,
        summary = KeysStrings.aimi_tube_basal_trim_summary,
        dependency = BooleanKey.OApsAIMIStraightLineTubeAdvisorEnabled,
        unitType = UnitType.DOUBLE_2),
    AimiTubeAggressiveness(
        key = "key_aimi_tube_aggressiveness",
        defaultValue = 1.0,
        min = 0.5,
        max = 2.0,
        title = KeysStrings.aimi_tube_aggressiveness_title,
        summary = KeysStrings.aimi_tube_aggressiveness_summary,
        dependency = BooleanKey.OApsAIMIStraightLineTubeAdvisorEnabled,
        unitType = UnitType.DOUBLE_2),
    AimiTubeHyperBandMgdl(
        key = "key_aimi_tube_hyper_band_mgdl",
        defaultValue = 35.0,
        min = 15.0,
        max = 55.0,
        title = KeysStrings.aimi_tube_hyper_band_title,
        summary = KeysStrings.aimi_tube_hyper_band_summary,
        dependency = BooleanKey.OApsAIMIStraightLineTubeAdvisorEnabled,
        unitType = UnitType.MGDL),
    AimiTubeHypoFloorMgdl(
        key = "key_aimi_tube_hypo_floor_mgdl",
        defaultValue = 72.0,
        min = 65.0,
        max = 90.0,
        title = KeysStrings.aimi_tube_hypo_floor_title,
        summary = KeysStrings.aimi_tube_hypo_floor_summary,
        dependency = BooleanKey.OApsAIMIStraightLineTubeAdvisorEnabled,
        unitType = UnitType.MGDL),
    AimiCosineGateMaxSensitivity( "aimi_cosine_gate_max_sens", 1.3, 1.0, 2.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    AimiCosineGateMinSensitivity( "aimi_cosine_gate_min_sens", 0.7, 0.5, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    AimiCosineGateMinDataQuality( "aimi_cosine_gate_min_dq", 0.3, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    AimiCosineGateAlpha( "aimi_cosine_gate_alpha", 2.0, 0.1, 10.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    AimiEndometriosisSmbDampen( "aimi_endo_smb_dampen", 0.7, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    AimiEndometriosisBasalMult( "aimi_endo_basal_mult", 1.3, 1.0, 2.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMILastEstimatedCarbTime( key = "OApsAIMILastEstimatedCarbTime", defaultValue = 0.0, min = 0.0, max = 20000000000000.0, title = TextRef.Literal("")),
    OApsAIMILastEstimatedCarbs( key = "OApsAIMILastEstimatedCarbs", defaultValue = 0.0, min = 0.0, max = 300.0, title = TextRef.Literal(""), unitType = UnitType.GRAMS),
    AimiUamConfidence ( key = "AIMI_UAM_CONFIDENCE", defaultValue = 0.5, min = 0.0, max = 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIDeltaPosRelease( key = "OApsAIMIDeltaPosRelease", defaultValue = 1.0, min = 0.5, max = 3.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIAntiStallBias( key = "OApsAIMIAntiStallBias", defaultValue = 0.10, min = 0.0, max = 0.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2), // biais de “décollage” anti-stagnation (+%),
    OApsAIMIZeroResumeFrac( key = "OApsAIMIZeroResumeFrac", defaultValue = 0.25, min = 0.05, max = 0.8, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIKickerMinUph( key = "OApsAIMIKickerMinUph", defaultValue = 0.2, min = 0.05, max = 1.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN_RATE),
    OApsAIMIKickerStep( key = "OApsAIMIKickerStep", defaultValue = 0.15, min = 0.05, max = 0.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2), // intensité du “kicker” plateau (incrément multiplicatif),
    OApsAIMIMaxMultiplier( key = "OApsAIMIMaxMultiplier", defaultValue = 1.6, min = 1.0, max = 2.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE), // plafond multiplicatif de la basale (× profil),
    OApsAIMIR2Confident( key = "OApsAIMIR2Confident", defaultValue = 0.7, min = 0.3, max = 0.95, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIPlateauBandAbs( key = "OApsAIMIPlateauBandAbs", defaultValue = 2.5, min = 0.5, max = 6.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE), // bande de tolérance du plateau (|Δ| ≤ X mg/dL/5m),
    OApsAIMIHyperDeepDevMgdl(
        key = "key_aimi_hyper_deep_dev_mgdl",
        defaultValue = 0.0,
        min = 0.0,
        max = 200.0,
        title = KeysStrings.pref_title_aimi_hyper_deep_dev,
        summary = KeysStrings.pref_summary_aimi_hyper_deep_dev,
        dependency = BooleanKey.OApsAIMIHyperTrajectoryRelease,
        unitType = UnitType.MGDL),
    OApsAIMIHyperEstablishedDevMgdl(
        key = "key_aimi_hyper_established_dev_mgdl",
        defaultValue = 0.0,
        min = 0.0,
        max = 160.0,
        title = KeysStrings.pref_title_aimi_hyper_established_dev,
        summary = KeysStrings.pref_summary_aimi_hyper_established_dev,
        dependency = BooleanKey.OApsAIMIHyperTrajectoryRelease,
        unitType = UnitType.MGDL),
    OApsAIMIHighBg(
        key = "OApsAIMIHighBg",
        defaultValue = 180.0,
        min = 140.0,
        max = 250.0,
        title = KeysStrings.pref_title_aimi_high_bg,
        summary = KeysStrings.pref_summary_aimi_high_bg,
        unitType = UnitType.MGDL),
    OApsAIMIActivityBasalCapFactor( "key_aimi_activity_basal_cap_factor", 1.3, 0.5, 3.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMINightGrowthMaxIobExtra( "key_oaps_aimi_ngr_max_iob_extra", 0.5, 0.0, 3.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMINightGrowthMaxSmbClamp( "key_oaps_aimi_ngr_max_smb_clamp", 1.2, 0.1, 5.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMINightGrowthBasalMultiplier( "key_oaps_aimi_ngr_basal_multiplier", 1.1, 1.0, 1.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMINightGrowthSmbMultiplier( "key_oaps_aimi_ngr_smb_multiplier", 1.2, 1.0, 1.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMINightGrowthMinRiseSlope( "key_oaps_aimi_ngr_min_rise_slope", 5.0, 0.5, 30.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIWCycleClampMax( "key_wcycle_clamp_max", 1.25, 1.0, 2.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIWCycleClampMin( "key_wcycle_clamp_min", 0.8, 0.5, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIwcycledateday( "key_wcycledateday", 1.0, 1.0, 31.0, title = TextRef.Literal("")),
    OApsAIMIHighCarbPrebolus2( "key_prebolus_highcarb_mode2", 5.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIHighCarbPrebolus( "key_prebolus_highcarb_mode", 5.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMISnackPrebolus( "key_prebolus_snack_mode", 1.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIDinnerPrebolus2( "key_prebolus2_dinner_mode", 2.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIDinnerPrebolus( "key_prebolus_dinner_mode", 2.5, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMILunchPrebolus2( "key_prebolus2_lunch_mode", 2.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMILunchPrebolus( "key_prebolus_lunch_mode", 2.5, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIAutodriveAcceleration( "key_Acceleration_autodrive_mode", 1.0, 0.1, 5.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIAutodriveDeviation( "key_mindeviation_autodrive_mode", 1.0, 0.1, 5.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIcombinedDelta( "key_combinedDelta_autodrive_mode", 1.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    autodriveMaxBasal( "autodrive_max_basal", 1.0, 0.05, 25.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN_RATE),
    meal_modes_MaxBasal( "meal_modes_max_basal", 1.0, 0.05, 25.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN_RATE),
    OApsAIMIautodrivesmallPrebolus(
        key = "key_prebolussmall_autodrive_mode",
        defaultValue = 0.1,
        min = 0.05,
        max = 20.0,
        title = KeysStrings.pref_title_aimi_autodrive_small_prebolus,
        summary = KeysStrings.aimi_summary_o_aps_a_i_m_iautodrivesmall_prebolus,
        dependency = BooleanKey.OApsAIMIautoDriveActive,
        unitType = UnitType.INSULIN),
    OApsAIMIautodrivePrebolus(
        key = "key_prebolus_autodrive_mode",
        defaultValue = 1.0,
        min = 0.1,
        max = 20.0,
        title = KeysStrings.pref_title_aimi_autodrive_prebolus,
        summary = KeysStrings.aimi_summary_o_aps_a_i_m_iautodrive_prebolus,
        dependency = BooleanKey.OApsAIMIautoDriveActive,
        unitType = UnitType.INSULIN),
    OApsAIMIMealPrebolus( "key_prebolus_meal_mode", 2.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIsleepFactor( "key_oaps_aimi_sleep_factor", 60.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMISnackFactor( "key_oaps_aimi_snack_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIHCFactor( "key_oaps_aimi_HC_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIDinnerFactor( "key_oaps_aimi_dinner_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMILunchFactor( "key_oaps_aimi_lunch_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIBFPrebolus2( "key_prebolus2_BF_mode", 2.0, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIBFPrebolus( "key_prebolus_BF_mode", 2.5, 0.1, 20.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIBFFactor( "key_oaps_aimi_BF_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIFCLFactor( "key_oaps_aimi_FCL_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIMealFactor( "key_oaps_aimi_meal_factor", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.PERCENT),
    OApsAIMIPriorityMaxIobExtraU( "aimi_priority_max_iob_extra_u", 2.0, 0.0, 5.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMIPriorityMaxIobFactor( "aimi_priority_max_iob_factor", 1.20, 1.0, 1.6, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIRedCarpetRestoreThreshold( "aimi_red_carpet_restore_threshold", 0.75, 0.50, 0.95, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIPkpdPragmaticReliefMinFactor( "aimi_pkpd_pragmatic_relief_min_factor", 0.75, 0.50, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMISmbLateFatDamping( "aimi_smb_late_fat_damping", 0.7, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMISmbExerciseDamping( "aimi_smb_exercise_damping", 0.6, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMISmbTailDamping( "aimi_smb_tail_damping", 0.85, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMISmbTailThreshold( "aimi_smb_tail_threshold", 0.25, 0.0, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIDynIsfTrajectoryMaxFraction(
        key = "aimi_dyn_isf_trajectory_max_fraction",
        defaultValue = 0.06,
        min = 0.02,
        max = 0.12,
        title = KeysStrings.pref_title_aimi_dyn_isf_trajectory_max_fraction,
        summary = KeysStrings.pref_summary_aimi_dyn_isf_trajectory_max_fraction,
        dependency = BooleanKey.OApsAIMIDynIsfTrajectoryTuningEnabled,
        unitType = UnitType.DOUBLE_3),
    OApsAIMIIsfFusionMaxChangePerTick( "aimi_isf_fusion_max_change_per_tick", 0.4, 0.0, 0.5, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIIsfFusionMaxFactor( "aimi_isf_fusion_max_factor", 2.0, 1.0, 2.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIIsfFusionMinFactor( "aimi_isf_fusion_min_factor", 0.75, 0.3, 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIDiaGovernorLearnedWeight( key = "aimi_dia_governor_learned_weight", defaultValue = 0.45, min = 0.0, max = 1.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIPeakGovernorLearnedWeight(
        key = "aimi_peak_governor_learned_weight",
        defaultValue = 0.55,
        min = 0.0,
        max = 1.0,
        title = KeysStrings.pref_title_aimi_peak_governor_learned_weight,
        summary = KeysStrings.pref_summary_aimi_peak_governor_learned_weight,
        unitType = UnitType.DOUBLE_2
    ),
    OApsAIMIPkpdStateEffectivePeak( "aimi_pkpd_state_effective_peak", 75.0, 35.0, 300.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStateTrajectoryPeak( "aimi_pkpd_state_traj_peak", 0.0, -100.0, 100.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStateSitePeak( "aimi_pkpd_state_site_peak", 0.0, -100.0, 100.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStatePhysioPeak( "aimi_pkpd_state_physio_peak", 0.0, -100.0, 100.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStatePriorPeak( "aimi_pkpd_state_prior_peak", 75.0, 0.0, 300.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStateInitializedAtEpochMs( "aimi_pkpd_state_initialized_at_ms", 0.0, 0.0, 4000000000000.0, title = TextRef.Literal("")),
    OApsAIMIPkpdStatePeakMin( "aimi_pkpd_state_peak_min", 75.0, 40.0, 300.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdStateDiaH( "aimi_pkpd_state_dia_h", 6.0, 4.0, 24.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMIPkpdMaxPeakChangePerDayMin( "aimi_pkpd_max_peak_change_per_day_min", 20.0, 1.0, 60.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdMaxDiaChangePerDayH( "aimi_pkpd_max_dia_change_per_day_h", 3.0, 0.1, 6.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMIPkpdBoundsPeakMinMax( "aimi_pkpd_bounds_peak_min_max", 240.0, 60.0, 480.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdBoundsPeakMinMin( "aimi_pkpd_bounds_peak_min_min", 30.0, 20.0, 240.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdBoundsDiaMaxH( "aimi_pkpd_bounds_dia_max_h", 24.0, 6.0, 36.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMIPkpdBoundsDiaMinH( "aimi_pkpd_bounds_dia_min_h", 4.0, 4.0, 24.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMIPkpdAnchorPeakMin( "aimi_pkpd_anchor_peak_min", 75.0, 35.0, 180.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdAnchorDiaH( "aimi_pkpd_anchor_dia_h", 4.0, 4.0, 12.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMIPkpdInitialPeakMin( "aimi_pkpd_initial_peak_min", 75.0, 35.0, 300.0, title = TextRef.Literal(""), unitType = UnitType.MIN),
    OApsAIMIPkpdInitialDiaH( "aimi_pkpd_initial_dia_h", 6.0, 4.0, 24.0, title = TextRef.Literal(""), unitType = UnitType.HOURS_DOUBLE),
    OApsAIMITDD7( "key_tdd7", 40.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),
    OApsAIMICHO( "key_cho", 50.0, 1.0, 150.0, title = TextRef.Literal(""), unitType = UnitType.GRAMS),
    OApsAIMIMpcInsulinUPerKgPerStep( "aimi_mpc_insulin_u_per_kg_per_5min", 0.065, 0.03, 0.12, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_3),
    OApsAIMIweight( "key_aimiweight", 50.0, 1.0, 200.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE),
    OApsAIMIHighBGMaxSMB( "key_openapsaimi_high_bg_max_smb", 1.0, 0.05, 30.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    OApsAIMIMaxSMB( "key_openapsaimi_max_smb", 1.0, 0.05, 30.0, title = TextRef.Literal(""), unitType = UnitType.DOUBLE_2),
    EquilMaxBolus( "equil_maxbolus", 10.0, 0.1, 25.0, title = TextRef.Literal(""), unitType = UnitType.INSULIN),

    ;

}
